language: python
matrix:
  include:
  - python: 3.6
    env: TOX_ENV=py36
  - python: 3.7
    env: TOX_ENV=py37
  - python: 3.7
    env: TOX_ENV=lint
before_install:
- sudo apt-get -y install libvirt-dev
install:
- pip install tox
script:
- tox -e $TOX_ENV
