name: Upload OBS Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish to OBS
      uses: tspmelo/publish-obs-action@master
      with:
        obs user:  ${{ secrets.OBS_USERNAME }}
        obs pass:  ${{ secrets.OBS_PASSWORD }}
        obs email:  ${{ secrets.OBS_EMAIL }}
        obs project:  ${{ secrets.OBS_PROJECT }}
        obs package:  ${{ secrets.OBS_PACKAGE }}
        full name:  ${{ secrets.FULL_NAME }}
